line-length = 120
indent-width = 4

[lint]
ignore = [
    "D",
    "ANN101",
    "ANN102",
    "ANN401",
    "FIX002",
    "TD001",
    "TD002",
    "TD003",
    "PERF401",
    "TID",
    "FBT",
    "PLR0913",
    "TCH002",
    "TCH003",
    "ISC001",
    "COM812",
    "INP001",
    "EXE002",
]

select = ["ALL"]

fixable = ["ALL"]
unfixable = ["B"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
force-single-line = true
